// <auto-generated />
using System;
using ChessGPT.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessGPT.PL.Migrations
{
    [DbContext(typeof(ChessGPTEntities))]
    partial class ChessGPTEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChessGPT.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameBoard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameState")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ba2a104-25c2-408f-ab57-306137019512"),
                            GameBoard = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w",
                            GameName = "First Game",
                            GameState = "o",
                            GameTime = new DateTime(2024, 2, 26, 17, 46, 37, 834, DateTimeKind.Local).AddTicks(7727)
                        },
                        new
                        {
                            Id = new Guid("5fab0ecc-8d69-4958-8ccb-540198d5c73c"),
                            GameBoard = "rnbqkbnr/pp1ppppp/8/2p5/4P3/5N2/PPPP1PPP/RNBQKB1R b",
                            GameName = "Second Game",
                            GameState = "o",
                            GameTime = new DateTime(2024, 2, 26, 17, 46, 37, 834, DateTimeKind.Local).AddTicks(7772)
                        },
                        new
                        {
                            Id = new Guid("8a9068dd-8e12-4203-819f-a21943fb0deb"),
                            GameBoard = "4K3/4p3/Bk1p4/b4rP1/2R3p1/P3PP2/P3N3/5r2 w",
                            GameName = "Third Game",
                            GameState = "o",
                            GameTime = new DateTime(2024, 2, 26, 17, 46, 37, 834, DateTimeKind.Local).AddTicks(7774)
                        });
                });

            modelBuilder.Entity("ChessGPT.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComputer")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c2cca4b-4a90-4f52-9275-1ee96c77f6ab"),
                            FirstName = "Kaiden",
                            IsComputer = false,
                            LastName = "Brunke",
                            Password = "W6ph5Mm5Pz8GgiULbPgzG37mj9g=",
                            UserName = "700233885"
                        },
                        new
                        {
                            Id = new Guid("3bfd9f6f-0f8e-4050-be90-77bbd01fff59"),
                            FirstName = "Logan",
                            IsComputer = false,
                            LastName = "Vang",
                            Password = "W6ph5Mm5Pz8GgiULbPgzG37mj9g=",
                            UserName = "500201348"
                        },
                        new
                        {
                            Id = new Guid("c1cb0628-b919-4297-a5bd-f86d1d9e3160"),
                            FirstName = "AI",
                            IsComputer = true,
                            LastName = "Robot",
                            Password = "W6ph5Mm5Pz8GgiULbPgzG37mj9g=",
                            UserName = "Robot"
                        });
                });

            modelBuilder.Entity("ChessGPT.PL.Entities.tblUserGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserGame_Id");

                    b.ToTable("tblUserGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d03b2de2-b2ad-4df1-8ed0-936c967ea1bf"),
                            Color = "w",
                            GameId = new Guid("3ba2a104-25c2-408f-ab57-306137019512"),
                            UserId = new Guid("8c2cca4b-4a90-4f52-9275-1ee96c77f6ab")
                        },
                        new
                        {
                            Id = new Guid("0a3d230b-e8f2-4c32-bdc9-ef1d223fd0ce"),
                            Color = "b",
                            GameId = new Guid("3ba2a104-25c2-408f-ab57-306137019512"),
                            UserId = new Guid("3bfd9f6f-0f8e-4050-be90-77bbd01fff59")
                        },
                        new
                        {
                            Id = new Guid("4cbde8b9-24ec-49a9-97c9-7f770982c03b"),
                            Color = "b",
                            GameId = new Guid("5fab0ecc-8d69-4958-8ccb-540198d5c73c"),
                            UserId = new Guid("8c2cca4b-4a90-4f52-9275-1ee96c77f6ab")
                        },
                        new
                        {
                            Id = new Guid("97dab6a7-4072-40ec-8654-a02f76d020a4"),
                            Color = "w",
                            GameId = new Guid("5fab0ecc-8d69-4958-8ccb-540198d5c73c"),
                            UserId = new Guid("3bfd9f6f-0f8e-4050-be90-77bbd01fff59")
                        },
                        new
                        {
                            Id = new Guid("7e7a85e0-5b9d-4582-8e27-29878a91ee4d"),
                            Color = "w",
                            GameId = new Guid("8a9068dd-8e12-4203-819f-a21943fb0deb"),
                            UserId = new Guid("c1cb0628-b919-4297-a5bd-f86d1d9e3160")
                        },
                        new
                        {
                            Id = new Guid("6ea4a8b8-2540-4640-89bb-dbcd9f6b3745"),
                            Color = "b",
                            GameId = new Guid("8a9068dd-8e12-4203-819f-a21943fb0deb"),
                            UserId = new Guid("8c2cca4b-4a90-4f52-9275-1ee96c77f6ab")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
